export const datas = {
    Badminton: "🏸",
    Baseball: "⚾️",
    Basketball: "🏀",
    Climbing: " 🧗",
    Cricket: "🏏",
    Bodyweighttraining: "💪",
    Gymandcrossfit: "🏋️",
    Cycling: "🚴",
    Darts: "🎯",
    Football: "⚽️",
    Hiking: "🌲",
    Rugby: "🏉",
    Running: "🏃",
    Skateboarding: "🛹",
    Skiing: "🎿",
    Snowboarding: "🏂",
    Spikeball: "🟡",
    TableTennis: "🏓",
    Tennis: "🎾",
    Volleyball: "🏐",
    Yoga: "🧘",
  };